name: Scheduled Tests with Allure Report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scheduled-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pytest requests allure-pytest
    - run: pytest test_echo.py --alluredir=allure-results
    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
    - run: allure generate allure-results -o allure-report --clean
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
        force_orphan: true
